# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dae390998ebfdc9288a6e50feee6485f2093d15b750f4ffc7af5a2e752c3256adfd8bc92c508f1e386d5d88039dbddd1db6a185020fe334f95fe99b8323c425b

test:
  secret_key_base: 5741c4cfc3c5a1667a95930569aabcb2338bf2380755c23e7440c5449eab2d9d22c2c9d033a38165bf96b04f0d64ec9ff0140f29582382b83c11f30a1c259d1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
